spring.application.name=product-health-service
server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pharmaflow_product}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Hibernate statistics - za N+1 detekciju
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.enabled=true

# Proper 404 za nepostojeće endpointe
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
