package com.pharmaflow.smartfeatures.migration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.junit.jupiter.api.Test;

class SmartFeatureMigrationTest {

  @Test
  void migrationShouldCreateInitialSchemaForFreshDatabase() throws Exception {
    String url =
        "jdbc:h2:mem:migration_fresh_schema;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";

    Flyway.configure().dataSource(url, "sa", "").load().migrate();

    try (Connection connection = DriverManager.getConnection(url, "sa", "");
        Statement statement = connection.createStatement();
        ResultSet resultSet =
            statement.executeQuery(
                "SELECT COUNT(*) FROM information_schema.tables WHERE table_name IN ('symptom', 'therapy_reminder', 'notification', 'faq_entry', 'fraud_rule')")) {
      assertThat(resultSet.next()).isTrue();
      assertThat(resultSet.getInt(1)).isEqualTo(5);
    }
  }

  @Test
  void migrationShouldBackfillNormalizedQuestionForExistingFaqRows() throws Exception {
    String url =
        "jdbc:h2:mem:migration_faq_backfill;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";

    try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
      try (Statement statement = connection.createStatement()) {
        statement.execute(
            """
                        CREATE TABLE faq_entry (
                            faq_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            question VARCHAR(200) NOT NULL,
                            answer VARCHAR(2000) NOT NULL,
                            category VARCHAR(30),
                            keywords VARCHAR(500),
                            is_active BOOLEAN NOT NULL,
                            updated_at TIMESTAMP NOT NULL
                        )
                        """);
        statement.executeUpdate(
            "INSERT INTO faq_entry (question, answer, category, keywords, is_active, updated_at) VALUES ('How   to pay?', 'Card', 'PAYMENTS', 'pay', TRUE, CURRENT_TIMESTAMP)");
      }
    }

    Flyway.configure().dataSource(url, "sa", "").baselineOnMigrate(true).load().migrate();

    try (Connection connection = DriverManager.getConnection(url, "sa", "");
        Statement statement = connection.createStatement();
        ResultSet resultSet =
            statement.executeQuery(
                "SELECT normalized_question FROM faq_entry WHERE question = 'How   to pay?'")) {
      assertThat(resultSet.next()).isTrue();
      assertThat(resultSet.getString("normalized_question")).isEqualTo("how to pay?");
    }
  }

  @Test
  void migrationShouldFailWhenFaqContainsWhitespaceDuplicates() throws Exception {
    String url =
        "jdbc:h2:mem:migration_faq_duplicates;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";

    try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
      try (Statement statement = connection.createStatement()) {
        statement.execute(
            """
                        CREATE TABLE faq_entry (
                            faq_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            question VARCHAR(200) NOT NULL,
                            answer VARCHAR(2000) NOT NULL,
                            category VARCHAR(30),
                            keywords VARCHAR(500),
                            is_active BOOLEAN NOT NULL,
                            updated_at TIMESTAMP NOT NULL
                        )
                        """);
        statement.executeUpdate(
            "INSERT INTO faq_entry (question, answer, category, keywords, is_active, updated_at) VALUES ('How to pay?', 'Card', 'PAYMENTS', 'pay', TRUE, CURRENT_TIMESTAMP)");
        statement.executeUpdate(
            "INSERT INTO faq_entry (question, answer, category, keywords, is_active, updated_at) VALUES ('How   to pay?', 'Card', 'PAYMENTS', 'pay', TRUE, CURRENT_TIMESTAMP)");
      }
    }

    Flyway flyway = Flyway.configure().dataSource(url, "sa", "").baselineOnMigrate(true).load();

    assertThatThrownBy(flyway::migrate)
        .isInstanceOf(FlywayException.class)
        .hasRootCauseMessage(
            "Cannot apply faq normalized_question uniqueness: duplicate normalized FAQ questions already exist. Clean up FAQ questions before rollout.");
  }

  @Test
  void migrationShouldBackfillNormalizedRuleNameForExistingFraudRules() throws Exception {
    String url =
        "jdbc:h2:mem:migration_rule_backfill;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";

    try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
      try (Statement statement = connection.createStatement()) {
        statement.execute(
            """
                        CREATE TABLE fraud_rule (
                            rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            rule_name VARCHAR(100) NOT NULL,
                            description VARCHAR(500),
                            weight DOUBLE PRECISION,
                            is_active BOOLEAN NOT NULL
                        )
                        """);
        statement.executeUpdate(
            "INSERT INTO fraud_rule (rule_name, description, weight, is_active) VALUES ('Late   pickup', 'desc', 10, TRUE)");
      }
    }

    Flyway.configure().dataSource(url, "sa", "").baselineOnMigrate(true).load().migrate();

    try (Connection connection = DriverManager.getConnection(url, "sa", "");
        Statement statement = connection.createStatement();
        ResultSet resultSet =
            statement.executeQuery(
                "SELECT normalized_rule_name FROM fraud_rule WHERE rule_name = 'Late   pickup'")) {
      assertThat(resultSet.next()).isTrue();
      assertThat(resultSet.getString("normalized_rule_name")).isEqualTo("late pickup");
    }
  }

  @Test
  void migrationShouldFailWhenSearchItemsContainDuplicates() throws Exception {
    String url =
        "jdbc:h2:mem:migration_search_item_duplicates;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";

    try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
      try (Statement statement = connection.createStatement()) {
        statement.execute(
            """
                        CREATE TABLE symptom_search_item (
                            search_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            search_id BIGINT NOT NULL,
                            symptom_id BIGINT NOT NULL
                        )
                        """);
        statement.executeUpdate(
            "INSERT INTO symptom_search_item (search_id, symptom_id) VALUES (1, 2)");
        statement.executeUpdate(
            "INSERT INTO symptom_search_item (search_id, symptom_id) VALUES (1, 2)");
      }
    }

    Flyway flyway = Flyway.configure().dataSource(url, "sa", "").baselineOnMigrate(true).load();

    assertThatThrownBy(flyway::migrate)
        .isInstanceOf(FlywayException.class)
        .hasRootCauseMessage(
            "Cannot apply symptom_search_item uniqueness: duplicate search/symptom pairs already exist. Clean up data before rollout.");
  }

  @Test
  void migrationShouldBackfillRecommendationActiveDimensionKey() throws Exception {
    String url =
        "jdbc:h2:mem:migration_recommendation_backfill;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";

    try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
      try (Statement statement = connection.createStatement()) {
        statement.execute(
            """
                        CREATE TABLE recommendation (
                            recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id BIGINT NOT NULL,
                            patient_profile_id BIGINT,
                            product_id BIGINT NOT NULL,
                            recommendation_type VARCHAR(50) NOT NULL,
                            score DOUBLE PRECISION,
                            reason_text VARCHAR(500),
                            generated_at TIMESTAMP NOT NULL,
                            expires_at TIMESTAMP,
                            status VARCHAR(30) NOT NULL
                        )
                        """);
        statement.executeUpdate(
            "INSERT INTO recommendation (user_id, patient_profile_id, product_id, recommendation_type, score, reason_text, generated_at, status) VALUES (10, 11, 12, 'FOR_YOU', 0.9, 'reason', CURRENT_TIMESTAMP, 'ACTIVE')");
        statement.executeUpdate(
            "INSERT INTO recommendation (user_id, patient_profile_id, product_id, recommendation_type, score, reason_text, generated_at, status) VALUES (10, 11, 12, 'FOR_YOU', 0.9, 'reason', CURRENT_TIMESTAMP, 'DISMISSED')");
      }
    }

    Flyway.configure()
        .dataSource(url, "sa", "")
        .baselineOnMigrate(true)
        .baselineVersion("4")
        .load()
        .migrate();

    try (Connection connection = DriverManager.getConnection(url, "sa", "");
        Statement statement = connection.createStatement();
        ResultSet activeResult =
            statement.executeQuery(
                "SELECT active_dimension_key FROM recommendation WHERE status = 'ACTIVE'")) {
      assertThat(activeResult.next()).isTrue();
      assertThat(activeResult.getString("active_dimension_key")).isEqualTo("10|11|12|FOR_YOU");
    }

    try (Connection connection = DriverManager.getConnection(url, "sa", "");
        Statement statement = connection.createStatement();
        ResultSet dismissedResult =
            statement.executeQuery(
                "SELECT active_dimension_key FROM recommendation WHERE status = 'DISMISSED'")) {
      assertThat(dismissedResult.next()).isTrue();
      assertThat(dismissedResult.getString("active_dimension_key")).isNull();
    }
  }

  @Test
  void migrationShouldFailWhenActiveRecommendationsContainDuplicates() throws Exception {
    String url =
        "jdbc:h2:mem:migration_recommendation_duplicates;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";

    try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
      try (Statement statement = connection.createStatement()) {
        statement.execute(
            """
                        CREATE TABLE recommendation (
                            recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id BIGINT NOT NULL,
                            patient_profile_id BIGINT,
                            product_id BIGINT NOT NULL,
                            recommendation_type VARCHAR(50) NOT NULL,
                            score DOUBLE PRECISION,
                            reason_text VARCHAR(500),
                            generated_at TIMESTAMP NOT NULL,
                            expires_at TIMESTAMP,
                            status VARCHAR(30) NOT NULL
                        )
                        """);
        statement.executeUpdate(
            "INSERT INTO recommendation (user_id, patient_profile_id, product_id, recommendation_type, score, reason_text, generated_at, status) VALUES (10, 11, 12, 'FOR_YOU', 0.9, 'reason', CURRENT_TIMESTAMP, 'ACTIVE')");
        statement.executeUpdate(
            "INSERT INTO recommendation (user_id, patient_profile_id, product_id, recommendation_type, score, reason_text, generated_at, status) VALUES (10, 11, 12, 'FOR_YOU', 0.8, 'reason', CURRENT_TIMESTAMP, 'ACTIVE')");
      }
    }

    Flyway flyway =
        Flyway.configure()
            .dataSource(url, "sa", "")
            .baselineOnMigrate(true)
            .baselineVersion("4")
            .load();

    assertThatThrownBy(flyway::migrate)
        .isInstanceOf(FlywayException.class)
        .hasRootCauseMessage(
            "Cannot apply recommendation active_dimension_key uniqueness: duplicate active recommendations already exist. Clean up recommendation data before rollout.");
  }

  @Test
  void migrationShouldRepairLegacyFraudLogScoreColumnWhenSchemaHistoryIsPastV7() throws Exception {
    String url =
        "jdbc:h2:mem:migration_fraud_log_repair;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE";

    try (Connection connection = DriverManager.getConnection(url, "sa", "")) {
      try (Statement statement = connection.createStatement()) {
        statement.execute(
            """
                        CREATE TABLE fraud_log (
                            fraud_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            fraud_check_id BIGINT NOT NULL,
                            rule_id BIGINT NOT NULL,
                            event_type VARCHAR(30) NOT NULL,
                            details VARCHAR(1000),
                            created_at TIMESTAMP NOT NULL
                        )
                        """);
      }
    }

    Flyway.configure()
        .dataSource(url, "sa", "")
        .baselineOnMigrate(true)
        .baselineVersion("8")
        .load()
        .migrate();

    try (Connection connection = DriverManager.getConnection(url, "sa", "");
        Statement statement = connection.createStatement();
        ResultSet resultSet =
            statement.executeQuery(
                "SELECT COUNT(*) FROM information_schema.columns WHERE table_name = 'fraud_log' AND column_name = 'score_contribution'")) {
      assertThat(resultSet.next()).isTrue();
      assertThat(resultSet.getInt(1)).isEqualTo(1);
    }
  }
}
