package com.pharmaflow.smartfeatures.model.notification;

import com.pharmaflow.smartfeatures.enums.notification.NotificationChannel;
import com.pharmaflow.smartfeatures.enums.notification.NotificationStatus;
import com.pharmaflow.smartfeatures.enums.notification.NotificationType;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Builder.Default;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** Represents a user notification generated by the smart features domain. */
@Entity
@Table(name = "notification")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Notification {

  /** Primary key of the notification. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "notification_id", nullable = false, updatable = false)
  private Long notificationId;

  /** Optional reminder that caused this notification. */
  @ManyToOne
  @JoinColumn(name = "reminder_id")
  private TherapyReminder therapyReminder;

  /** External reference to the user. */
  @NotNull
  @Positive
  @Column(name = "user_id", nullable = false)
  private Long userId;

  /** Optional external reference to the patient profile. */
  @Positive
  @Column(name = "patient_profile_id")
  private Long patientProfileId;

  /** Functional type of the notification. */
  @NotNull
  @Enumerated(EnumType.STRING)
  @Column(name = "type", nullable = false)
  private NotificationType type;

  /** Short title shown to the user. */
  @NotBlank
  @Size(max = 120)
  @Column(name = "title", nullable = false, length = 120)
  private String title;

  /** Main notification content. */
  @NotBlank
  @Size(max = 1000)
  @Column(name = "message", nullable = false, length = 1000)
  private String message;

  /** Delivery channel used for the notification. */
  @NotNull
  @Enumerated(EnumType.STRING)
  @Column(name = "channel", nullable = false)
  private NotificationChannel channel;

  /** Delivery lifecycle state. */
  @NotNull
  @Enumerated(EnumType.STRING)
  @Column(name = "status", nullable = false)
  private NotificationStatus status;

  /** Timestamp when the notification record was created. */
  @NotNull
  @Column(name = "created_at", nullable = false)
  private LocalDateTime createdAt;

  /** Optional timestamp when the notification was sent. */
  @Column(name = "sent_at")
  private LocalDateTime sentAt;

  /** Optional timestamp when the user read the notification. */
  @Column(name = "read_at")
  private LocalDateTime readAt;

  /** Causes or sources recorded for this notification. */
  @Default
  @OneToMany(mappedBy = "notification", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<NotificationTrigger> triggers = new ArrayList<>();
}
