package db.migration;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

public class V10__AddRecommendationReservationSaga extends BaseJavaMigration {

  @Override
  public void migrate(Context context) throws Exception {
    Connection connection = context.getConnection();
    if (!tableExists(connection, "recommendation")
        || tableExists(connection, "recommendation_reservation_saga")) {
      return;
    }
    try (Statement statement = connection.createStatement()) {
      statement.execute(
          """
          CREATE TABLE recommendation_reservation_saga (
              saga_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              correlation_id VARCHAR(36) NOT NULL,
              recommendation_id BIGINT NOT NULL,
              user_id BIGINT NOT NULL,
              patient_profile_id BIGINT,
              product_id BIGINT NOT NULL,
              pharmacy_id BIGINT NOT NULL,
              quantity INTEGER NOT NULL,
              reservation_id BIGINT,
              status VARCHAR(40) NOT NULL,
              failure_reason VARCHAR(500),
              created_at TIMESTAMP NOT NULL,
              updated_at TIMESTAMP NOT NULL,
              CONSTRAINT uk_recommendation_reservation_saga_correlation
                  UNIQUE (correlation_id),
              CONSTRAINT fk_recommendation_reservation_saga_recommendation
                  FOREIGN KEY (recommendation_id) REFERENCES recommendation(recommendation_id)
          )
          """);
    }
  }

  private boolean tableExists(Connection connection, String expectedTableName) throws SQLException {
    DatabaseMetaData metaData = connection.getMetaData();
    try (ResultSet tables = metaData.getTables(null, null, null, new String[] {"TABLE"})) {
      while (tables.next()) {
        if (expectedTableName.equalsIgnoreCase(tables.getString("TABLE_NAME"))) {
          return true;
        }
      }
      return false;
    }
  }
}
