package db.migration;

import java.sql.Connection;
import java.sql.Statement;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

public class V1__CreateSmartFeaturesSchema extends BaseJavaMigration {

  @Override
  public void migrate(Context context) throws Exception {
    Connection connection = context.getConnection();
    try (Statement statement = connection.createStatement()) {
      statement.execute(
          """
                    CREATE TABLE chat_session (
                        session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        patient_profile_id BIGINT,
                        session_type VARCHAR(30) NOT NULL,
                        status VARCHAR(30) NOT NULL,
                        started_at TIMESTAMP NOT NULL,
                        ended_at TIMESTAMP
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE faq_entry (
                        faq_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        question VARCHAR(200) NOT NULL,
                        answer VARCHAR(2000) NOT NULL,
                        category VARCHAR(30) NOT NULL,
                        keywords VARCHAR(500),
                        is_active BOOLEAN NOT NULL,
                        updated_at TIMESTAMP NOT NULL,
                        normalized_question VARCHAR(200) NOT NULL,
                        CONSTRAINT uk_faq_entry_normalized_question UNIQUE (normalized_question)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE fraud_rule (
                        rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        rule_name VARCHAR(100) NOT NULL,
                        rule_code VARCHAR(80) NOT NULL,
                        category VARCHAR(50) NOT NULL,
                        description VARCHAR(500),
                        weight DOUBLE PRECISION NOT NULL,
                        is_active BOOLEAN NOT NULL,
                        normalized_rule_name VARCHAR(100) NOT NULL,
                        CONSTRAINT uk_fraud_rule_normalized_name UNIQUE (normalized_rule_name),
                        CONSTRAINT uk_fraud_rule_code UNIQUE (rule_code)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE fraud_check (
                        fraud_check_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        order_id BIGINT NOT NULL,
                        checked_at TIMESTAMP NOT NULL,
                        risk_score DOUBLE PRECISION,
                        decision VARCHAR(30) NOT NULL
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE recommendation (
                        recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        patient_profile_id BIGINT,
                        product_id BIGINT NOT NULL,
                        recommendation_type VARCHAR(50) NOT NULL,
                        score DOUBLE PRECISION,
                        reason_text VARCHAR(500),
                        generated_at TIMESTAMP NOT NULL,
                        expires_at TIMESTAMP,
                        status VARCHAR(30) NOT NULL,
                        active_dimension_key VARCHAR(200),
                        CONSTRAINT uk_recommendation_active_dimension_key UNIQUE (active_dimension_key)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE symptom (
                        symptom_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        normalized_name VARCHAR(100) NOT NULL,
                        description VARCHAR(500),
                        severity_level VARCHAR(20),
                        is_active BOOLEAN NOT NULL,
                        CONSTRAINT uk_symptom_normalized_name UNIQUE (normalized_name)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE symptom_search (
                        search_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        patient_profile_id BIGINT,
                        search_query VARCHAR(255) NOT NULL,
                        searched_at TIMESTAMP NOT NULL
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE therapy_reminder (
                        reminder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        owner_user_id BIGINT NOT NULL DEFAULT 0,
                        patient_profile_id BIGINT NOT NULL,
                        product_id BIGINT NOT NULL,
                        dosage_instruction VARCHAR(500),
                        frequency_per_day INTEGER NOT NULL,
                        start_date DATE NOT NULL,
                        end_date DATE,
                        next_reminder_at TIMESTAMP,
                        status VARCHAR(30) NOT NULL
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE chat_message (
                        message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        session_id BIGINT NOT NULL,
                        sender_type VARCHAR(20) NOT NULL,
                        sender_id BIGINT,
                        message_text VARCHAR(2000),
                        attachment_url VARCHAR(1000),
                        created_at TIMESTAMP NOT NULL,
                        CONSTRAINT fk_chat_message_session
                            FOREIGN KEY (session_id) REFERENCES chat_session(session_id)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE chat_intent_match (
                        intent_match_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        message_id BIGINT NOT NULL UNIQUE,
                        faq_id BIGINT NOT NULL,
                        detected_intent VARCHAR(100) NOT NULL,
                        confidence_score DOUBLE PRECISION,
                        CONSTRAINT fk_chat_intent_match_message
                            FOREIGN KEY (message_id) REFERENCES chat_message(message_id),
                        CONSTRAINT fk_chat_intent_match_faq
                            FOREIGN KEY (faq_id) REFERENCES faq_entry(faq_id)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE fraud_log (
                        fraud_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        fraud_check_id BIGINT NOT NULL,
                        rule_id BIGINT NOT NULL,
                        event_type VARCHAR(30) NOT NULL,
                        details VARCHAR(1000),
                        score_contribution DOUBLE PRECISION,
                        created_at TIMESTAMP NOT NULL,
                        CONSTRAINT fk_fraud_log_check
                            FOREIGN KEY (fraud_check_id) REFERENCES fraud_check(fraud_check_id),
                        CONSTRAINT fk_fraud_log_rule
                            FOREIGN KEY (rule_id) REFERENCES fraud_rule(rule_id)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE recommendation_event (
                        event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        recommendation_id BIGINT NOT NULL,
                        event_type VARCHAR(30) NOT NULL,
                        event_time TIMESTAMP NOT NULL,
                        CONSTRAINT fk_recommendation_event_recommendation
                            FOREIGN KEY (recommendation_id) REFERENCES recommendation(recommendation_id)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE symptom_product_match (
                        match_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        symptom_id BIGINT NOT NULL,
                        product_id BIGINT NOT NULL,
                        relevance_score DOUBLE PRECISION,
                        match_reason VARCHAR(500),
                        CONSTRAINT uk_symptom_product_match_symptom_product UNIQUE (symptom_id, product_id),
                        CONSTRAINT fk_symptom_product_match_symptom
                            FOREIGN KEY (symptom_id) REFERENCES symptom(symptom_id)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE symptom_search_item (
                        search_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        search_id BIGINT NOT NULL,
                        symptom_id BIGINT NOT NULL,
                        CONSTRAINT uk_symptom_search_item_search_symptom UNIQUE (search_id, symptom_id),
                        CONSTRAINT fk_symptom_search_item_search
                            FOREIGN KEY (search_id) REFERENCES symptom_search(search_id),
                        CONSTRAINT fk_symptom_search_item_symptom
                            FOREIGN KEY (symptom_id) REFERENCES symptom(symptom_id)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE notification (
                        notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        reminder_id BIGINT,
                        user_id BIGINT NOT NULL,
                        patient_profile_id BIGINT,
                        type VARCHAR(30) NOT NULL,
                        channel VARCHAR(20) NOT NULL,
                        title VARCHAR(120) NOT NULL,
                        message VARCHAR(1000) NOT NULL,
                        status VARCHAR(30) NOT NULL,
                        created_at TIMESTAMP NOT NULL,
                        sent_at TIMESTAMP,
                        read_at TIMESTAMP,
                        CONSTRAINT fk_notification_reminder
                            FOREIGN KEY (reminder_id) REFERENCES therapy_reminder(reminder_id)
                    )
                    """);
      statement.execute(
          """
                    CREATE TABLE notification_trigger (
                        trigger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        notification_id BIGINT NOT NULL,
                        trigger_source VARCHAR(30) NOT NULL,
                        source_entity_id BIGINT,
                        triggered_at TIMESTAMP NOT NULL,
                        CONSTRAINT fk_notification_trigger_notification
                            FOREIGN KEY (notification_id) REFERENCES notification(notification_id)
                    )
                    """);
    }
  }
}
